import React from 'react'

const CarsTemp = [
  {
    make: 'Tesla',
    model: 'Model 3',
    image: 'https://tesla-cdn.thron.com/delivery/public/image/tesla/197be9d8-7cf6-49b8-a711-e56237fa874a/bvlatuR/std/1200x628/rhd-model-3-social',
    description: 'The Tesla Model 3 has quickly become one of the most popular electric cars on the market, and for good reason. It\'s an excellent car that combines style, performance, and eco-friendliness into one package. Here are some of the reasons why the Tesla Model 3 is considered by many to be the best electric car on the market.',
    performance: 'First and foremost, the Model 3\'s performance is unmatched. It can go from 0 to 60 mph in as little as 3.2 seconds, making it one of the fastest electric cars available. The car handles exceptionally well, with a low center of gravity and precise steering, making it a joy to drive on any road.',
    range: 'The Model 3 also has an impressive range of up to 358 miles on a single charge, depending on the model. This range is comparable to that of many gas-powered vehicles, making the Model 3 an excellent option for long-distance driving.',
    eco: 'In addition to its impressive performance and range, the Model 3 is also incredibly eco-friendly. It produces zero emissions, which helps reduce air pollution and combat climate change. It\'s also incredibly energy-efficient, with an MPGe (miles per gallon equivalent) rating of up to 141 city/127 highway.',
    design: 'Another factor that sets the Model 3 apart is its sleek and modern design. The car\'s aerodynamic profile not only looks great, but it also helps reduce drag and increase efficiency. The interior is spacious and minimalist, with a large touchscreen display that controls everything from music to climate control.',
    safety: 'Finally, the Model 3 is equipped with an impressive array of safety features, including forward collision warning, automatic emergency braking, and adaptive cruise control. These features, combined with the car\'s low center of gravity and excellent handling, make it one of the safest cars on the road.',
  },
  {
    make: 'Tesla',
    model: 'Model Y',
    image: 'https://tesla-cdn.thron.com/delivery/public/image/tesla/8bdb0faa-e77a-4072-aabd-0bb2e0a2454e/bvlatuR/std/1200x628/Model-Y-Social-Global?quality=auto-medium&format=auto',
    description: 'The Tesla Model Y is a mid-size crossover SUV that was unveiled in March 2019. It\'s the third vehicle in Tesla\'s lineup, following the Model S and Model X. The Model Y is a smaller, more affordable version of the Model X, and it\'s expected to be the company\'s best-selling vehicle. Here are some of the reasons why the Tesla Model Y is considered by many to be the best electric SUV on the market.',
    performance: 'The Model Y is powered by a dual-motor all-wheel drive system that produces 468 horsepower and 472 lb-ft of torque. It can go from 0 to 60 mph in as little as 3.5 seconds, making it one of the fastest electric SUVs available. The car handles exceptionally well, with a low center of gravity and precise steering, making it a joy to drive on any road.',
    range: 'The Model Y also has an impressive range of up to 326 miles on a single charge, depending on the model. This range is comparable to that of many gas-powered SUVs, making the Model Y an excellent option for long-distance driving.',
    eco: 'In addition to its impressive performance and range, the Model Y is also incredibly eco-friendly. It produces zero emissions, which helps reduce air pollution and combat climate change. It\'s also incredibly energy-efficient, with an MPGe (miles per gallon equivalent) rating of up to 141 city/127 highway.',
    design: 'Another factor that sets the Model Y apart is its sleek and modern design. The car\'s aerodynamic profile not only looks great, but it also helps reduce drag and increase efficiency. The interior is spacious and minimalist, with a large touchscreen display that controls everything from music to climate control.',
    safety: 'Finally, the Model Y is equipped with an impressive array of safety features, including forward collision warning, automatic emergency braking, and adaptive cruise control. These features, combined with the car\'s low center of gravity and excellent handling, make it one of the safest cars on the road.',
  },
  {
    make: 'Tesla',
    model: 'Model S',
    image: 'https://tesla-cdn.thron.com/delivery/public/image/tesla/9ed31f26-4d49-4701-bc5b-2121ff85e5b3/bvlatuR/std/2880x1800/Model-S-Main-Hero-Desktop-LHD?quality=auto-medium&amp;format=auto',
    description: 'The Tesla Model S is a full-size luxury sedan that was unveiled in 2012. It\'s the first vehicle in Tesla\'s lineup, and it\'s considered by many to be the best electric car on the market. Here are some of the reasons why the Tesla Model S is considered by many to be the best electric car on the market.',
    performance: 'The Model S is powered by a dual-motor all-wheel drive system that produces 402 horsepower and 416 lb-ft of torque. It can go from 0 to 60 mph in as little as 2.5 seconds, making it one of the fastest electric cars available. The car handles exceptionally well, with a low center of gravity and precise steering, making it a joy to drive on any road.',
    range: 'The Model S also has an impressive range of up to 402 miles on a single charge, depending on the model. This range is comparable to that of many gas-powered vehicles, making the Model S an excellent option for long-distance driving.',
    eco: 'In addition to its impressive performance and range, the Model S is also incredibly eco-friendly. It produces zero emissions, which helps reduce air pollution and combat climate change. It\'s also incredibly energy-efficient, with an MPGe (miles per gallon equivalent) rating of up to 141 city/127 highway.',
    design: 'Another factor that sets the Model S apart is its sleek and modern design. The car\'s aerodynamic profile not only looks great, but it also helps reduce drag and increase efficiency. The interior is spacious and minimalist, with a large touchscreen display that controls everything from music to climate control.',
    safety: 'Finally, the Model S is equipped with an impressive array of safety features, including forward collision warning, automatic emergency braking, and adaptive cruise control. These features, combined with the car\'s low center of gravity and excellent handling, make it one of the safest cars on the road.',
  },
  {
    make: 'Tesla',
    model: 'Model X',
    image: 'https://tesla-cdn.thron.com/delivery/public/image/tesla/458cfaaf-de1e-47e0-867e-cb78c1993db3/bvlatuR/std/1200x628/Model-X-Social?quality=auto-medium&format=auto',
    description: 'The Tesla Model X is a full-size luxury crossover SUV that was unveiled in 2015. It\'s the second vehicle in Tesla\'s lineup, following the Model S. The Model X is a larger, more expensive version of the Model S, and it\'s considered by many to be the best electric SUV on the market. Here are some of the reasons why the Tesla Model X is considered by many to be the best electric SUV on the market.',
    performance: 'The Model X is powered by a dual-motor all-wheel drive system that produces 518 horsepower and 568 lb-ft of torque. It can go from 0 to 60 mph in as little as 2.6 seconds, making it one of the fastest electric SUVs available. The car handles exceptionally well, with a low center of gravity and precise steering, making it a joy to drive on any road.',
    range: 'The Model X also has an impressive range of up to 351 miles on a single charge, depending on the model. This range is comparable to that of many gas-powered SUVs, making the Model X an excellent option for long-distance driving.',
    eco: 'In addition to its impressive performance and range, the Model X is also incredibly eco-friendly. It produces zero emissions, which helps reduce air pollution and combat climate change. It\'s also incredibly energy-efficient, with an MPGe (miles per gallon equivalent) rating of up to 141 city/127 highway.',
    design: 'Another factor that sets the Model X apart is its sleek and modern design. The car\'s aerodynamic profile not only looks great, but it also helps reduce drag and increase efficiency. The interior is spacious and minimalist, with a large touchscreen display that controls everything from music to climate control.',
    safety: 'Finally, the Model X is equipped with an impressive array of safety features, including forward collision warning, automatic emergency braking, and adaptive cruise control. These features, combined with the car\'s low center of gravity and excellent handling, make it one of the safest cars on the road.',
  },
  {
    make: 'Tesla',
    model: 'Model 3',
    image: 'https://tesla-cdn.thron.com/delivery/public/image/tesla/197be9d8-7cf6-49b8-a711-e56237fa874a/bvlatuR/std/1200x628/rhd-model-3-social',
    description: 'The Tesla Model 3 has quickly become one of the most popular electric cars on the market, and for good reason. It\'s an excellent car that combines style, performance, and eco-friendliness into one package. Here are some of the reasons why the Tesla Model 3 is considered by many to be the best electric car on the market.',
    performance: 'First and foremost, the Model 3\'s performance is unmatched. It can go from 0 to 60 mph in as little as 3.2 seconds, making it one of the fastest electric cars available. The car handles exceptionally well, with a low center of gravity and precise steering, making it a joy to drive on any road.',
    range: 'The Model 3 also has an impressive range of up to 358 miles on a single charge, depending on the model. This range is comparable to that of many gas-powered vehicles, making the Model 3 an excellent option for long-distance driving.',
    eco: 'In addition to its impressive performance and range, the Model 3 is also incredibly eco-friendly. It produces zero emissions, which helps reduce air pollution and combat climate change. It\'s also incredibly energy-efficient, with an MPGe (miles per gallon equivalent) rating of up to 141 city/127 highway.',
    design: 'Another factor that sets the Model 3 apart is its sleek and modern design. The car\'s aerodynamic profile not only looks great, but it also helps reduce drag and increase efficiency. The interior is spacious and minimalist, with a large touchscreen display that controls everything from music to climate control.',
    safety: 'Finally, the Model 3 is equipped with an impressive array of safety features, including forward collision warning, automatic emergency braking, and adaptive cruise control. These features, combined with the car\'s low center of gravity and excellent handling, make it one of the safest cars on the road.',
  },
  {
    make: 'Tesla',
    model: 'Model 3',
    image: 'https://tesla-cdn.thron.com/delivery/public/image/tesla/197be9d8-7cf6-49b8-a711-e56237fa874a/bvlatuR/std/1200x628/rhd-model-3-social',
    description: 'The Tesla Model 3 has quickly become one of the most popular electric cars on the market, and for good reason. It\'s an excellent car that combines style, performance, and eco-friendliness into one package. Here are some of the reasons why the Tesla Model 3 is considered by many to be the best electric car on the market.',
    performance: 'First and foremost, the Model 3\'s performance is unmatched. It can go from 0 to 60 mph in as little as 3.2 seconds, making it one of the fastest electric cars available. The car handles exceptionally well, with a low center of gravity and precise steering, making it a joy to drive on any road.',
    range: 'The Model 3 also has an impressive range of up to 358 miles on a single charge, depending on the model. This range is comparable to that of many gas-powered vehicles, making the Model 3 an excellent option for long-distance driving.',
    eco: 'In addition to its impressive performance and range, the Model 3 is also incredibly eco-friendly. It produces zero emissions, which helps reduce air pollution and combat climate change. It\'s also incredibly energy-efficient, with an MPGe (miles per gallon equivalent) rating of up to 141 city/127 highway.',
    design: 'Another factor that sets the Model 3 apart is its sleek and modern design. The car\'s aerodynamic profile not only looks great, but it also helps reduce drag and increase efficiency. The interior is spacious and minimalist, with a large touchscreen display that controls everything from music to climate control.',
    safety: 'Finally, the Model 3 is equipped with an impressive array of safety features, including forward collision warning, automatic emergency braking, and adaptive cruise control. These features, combined with the car\'s low center of gravity and excellent handling, make it one of the safest cars on the road.',
  },
]

export default CarsTemp