import React from 'react'

const CarsTemp = [
  {
    make: 'Tesla',
    model: 'Model 3',
    image: 'https://tesla-cdn.thron.com/delivery/public/image/tesla/197be9d8-7cf6-49b8-a711-e56237fa874a/bvlatuR/std/1200x628/rhd-model-3-social',
    description: 'The Tesla Model 3 has quickly become one of the most popular electric cars on the market, and for good reason. It\'s an excellent car that combines style, performance, and eco-friendliness into one package. Here are some of the reasons why the Tesla Model 3 is considered by many to be the best electric car on the market.',
    performance: 'First and foremost, the Model 3\'s performance is unmatched. It can go from 0 to 60 mph in as little as 3.2 seconds, making it one of the fastest electric cars available. The car handles exceptionally well, with a low center of gravity and precise steering, making it a joy to drive on any road.',
    range: 'The Model 3 also has an impressive range of up to 358 miles on a single charge, depending on the model. This range is comparable to that of many gas-powered vehicles, making the Model 3 an excellent option for long-distance driving.',
    eco: 'In addition to its impressive performance and range, the Model 3 is also incredibly eco-friendly. It produces zero emissions, which helps reduce air pollution and combat climate change. It\'s also incredibly energy-efficient, with an MPGe (miles per gallon equivalent) rating of up to 141 city/127 highway.',
    design: 'Another factor that sets the Model 3 apart is its sleek and modern design. The car\'s aerodynamic profile not only looks great, but it also helps reduce drag and increase efficiency. The interior is spacious and minimalist, with a large touchscreen display that controls everything from music to climate control.',
    safety: 'Finally, the Model 3 is equipped with an impressive array of safety features, including forward collision warning, automatic emergency braking, and adaptive cruise control. These features, combined with the car\'s low center of gravity and excellent handling, make it one of the safest cars on the road.',
  },
  {
    make: 'Tesla',
    model: 'Model 3',
    image: 'https://tesla-cdn.thron.com/delivery/public/image/tesla/197be9d8-7cf6-49b8-a711-e56237fa874a/bvlatuR/std/1200x628/rhd-model-3-social',
    description: 'The Tesla Model 3 has quickly become one of the most popular electric cars on the market, and for good reason. It\'s an excellent car that combines style, performance, and eco-friendliness into one package. Here are some of the reasons why the Tesla Model 3 is considered by many to be the best electric car on the market.',
    performance: 'First and foremost, the Model 3\'s performance is unmatched. It can go from 0 to 60 mph in as little as 3.2 seconds, making it one of the fastest electric cars available. The car handles exceptionally well, with a low center of gravity and precise steering, making it a joy to drive on any road.',
    range: 'The Model 3 also has an impressive range of up to 358 miles on a single charge, depending on the model. This range is comparable to that of many gas-powered vehicles, making the Model 3 an excellent option for long-distance driving.',
    eco: 'In addition to its impressive performance and range, the Model 3 is also incredibly eco-friendly. It produces zero emissions, which helps reduce air pollution and combat climate change. It\'s also incredibly energy-efficient, with an MPGe (miles per gallon equivalent) rating of up to 141 city/127 highway.',
    design: 'Another factor that sets the Model 3 apart is its sleek and modern design. The car\'s aerodynamic profile not only looks great, but it also helps reduce drag and increase efficiency. The interior is spacious and minimalist, with a large touchscreen display that controls everything from music to climate control.',
    safety: 'Finally, the Model 3 is equipped with an impressive array of safety features, including forward collision warning, automatic emergency braking, and adaptive cruise control. These features, combined with the car\'s low center of gravity and excellent handling, make it one of the safest cars on the road.',
  },
  {
    make: 'Tesla',
    model: 'Model 3',
    image: 'https://tesla-cdn.thron.com/delivery/public/image/tesla/197be9d8-7cf6-49b8-a711-e56237fa874a/bvlatuR/std/1200x628/rhd-model-3-social',
    description: 'The Tesla Model 3 has quickly become one of the most popular electric cars on the market, and for good reason. It\'s an excellent car that combines style, performance, and eco-friendliness into one package. Here are some of the reasons why the Tesla Model 3 is considered by many to be the best electric car on the market.',
    performance: 'First and foremost, the Model 3\'s performance is unmatched. It can go from 0 to 60 mph in as little as 3.2 seconds, making it one of the fastest electric cars available. The car handles exceptionally well, with a low center of gravity and precise steering, making it a joy to drive on any road.',
    range: 'The Model 3 also has an impressive range of up to 358 miles on a single charge, depending on the model. This range is comparable to that of many gas-powered vehicles, making the Model 3 an excellent option for long-distance driving.',
    eco: 'In addition to its impressive performance and range, the Model 3 is also incredibly eco-friendly. It produces zero emissions, which helps reduce air pollution and combat climate change. It\'s also incredibly energy-efficient, with an MPGe (miles per gallon equivalent) rating of up to 141 city/127 highway.',
    design: 'Another factor that sets the Model 3 apart is its sleek and modern design. The car\'s aerodynamic profile not only looks great, but it also helps reduce drag and increase efficiency. The interior is spacious and minimalist, with a large touchscreen display that controls everything from music to climate control.',
    safety: 'Finally, the Model 3 is equipped with an impressive array of safety features, including forward collision warning, automatic emergency braking, and adaptive cruise control. These features, combined with the car\'s low center of gravity and excellent handling, make it one of the safest cars on the road.',
  },
  {
    make: 'Tesla',
    model: 'Model 3',
    image: 'https://tesla-cdn.thron.com/delivery/public/image/tesla/197be9d8-7cf6-49b8-a711-e56237fa874a/bvlatuR/std/1200x628/rhd-model-3-social',
    description: 'The Tesla Model 3 has quickly become one of the most popular electric cars on the market, and for good reason. It\'s an excellent car that combines style, performance, and eco-friendliness into one package. Here are some of the reasons why the Tesla Model 3 is considered by many to be the best electric car on the market.',
    performance: 'First and foremost, the Model 3\'s performance is unmatched. It can go from 0 to 60 mph in as little as 3.2 seconds, making it one of the fastest electric cars available. The car handles exceptionally well, with a low center of gravity and precise steering, making it a joy to drive on any road.',
    range: 'The Model 3 also has an impressive range of up to 358 miles on a single charge, depending on the model. This range is comparable to that of many gas-powered vehicles, making the Model 3 an excellent option for long-distance driving.',
    eco: 'In addition to its impressive performance and range, the Model 3 is also incredibly eco-friendly. It produces zero emissions, which helps reduce air pollution and combat climate change. It\'s also incredibly energy-efficient, with an MPGe (miles per gallon equivalent) rating of up to 141 city/127 highway.',
    design: 'Another factor that sets the Model 3 apart is its sleek and modern design. The car\'s aerodynamic profile not only looks great, but it also helps reduce drag and increase efficiency. The interior is spacious and minimalist, with a large touchscreen display that controls everything from music to climate control.',
    safety: 'Finally, the Model 3 is equipped with an impressive array of safety features, including forward collision warning, automatic emergency braking, and adaptive cruise control. These features, combined with the car\'s low center of gravity and excellent handling, make it one of the safest cars on the road.',
  },
  {
    make: 'Tesla',
    model: 'Model 3',
    image: 'https://tesla-cdn.thron.com/delivery/public/image/tesla/197be9d8-7cf6-49b8-a711-e56237fa874a/bvlatuR/std/1200x628/rhd-model-3-social',
    description: 'The Tesla Model 3 has quickly become one of the most popular electric cars on the market, and for good reason. It\'s an excellent car that combines style, performance, and eco-friendliness into one package. Here are some of the reasons why the Tesla Model 3 is considered by many to be the best electric car on the market.',
    performance: 'First and foremost, the Model 3\'s performance is unmatched. It can go from 0 to 60 mph in as little as 3.2 seconds, making it one of the fastest electric cars available. The car handles exceptionally well, with a low center of gravity and precise steering, making it a joy to drive on any road.',
    range: 'The Model 3 also has an impressive range of up to 358 miles on a single charge, depending on the model. This range is comparable to that of many gas-powered vehicles, making the Model 3 an excellent option for long-distance driving.',
    eco: 'In addition to its impressive performance and range, the Model 3 is also incredibly eco-friendly. It produces zero emissions, which helps reduce air pollution and combat climate change. It\'s also incredibly energy-efficient, with an MPGe (miles per gallon equivalent) rating of up to 141 city/127 highway.',
    design: 'Another factor that sets the Model 3 apart is its sleek and modern design. The car\'s aerodynamic profile not only looks great, but it also helps reduce drag and increase efficiency. The interior is spacious and minimalist, with a large touchscreen display that controls everything from music to climate control.',
    safety: 'Finally, the Model 3 is equipped with an impressive array of safety features, including forward collision warning, automatic emergency braking, and adaptive cruise control. These features, combined with the car\'s low center of gravity and excellent handling, make it one of the safest cars on the road.',
  },
  {
    make: 'Tesla',
    model: 'Model 3',
    image: 'https://tesla-cdn.thron.com/delivery/public/image/tesla/197be9d8-7cf6-49b8-a711-e56237fa874a/bvlatuR/std/1200x628/rhd-model-3-social',
    description: 'The Tesla Model 3 has quickly become one of the most popular electric cars on the market, and for good reason. It\'s an excellent car that combines style, performance, and eco-friendliness into one package. Here are some of the reasons why the Tesla Model 3 is considered by many to be the best electric car on the market.',
    performance: 'First and foremost, the Model 3\'s performance is unmatched. It can go from 0 to 60 mph in as little as 3.2 seconds, making it one of the fastest electric cars available. The car handles exceptionally well, with a low center of gravity and precise steering, making it a joy to drive on any road.',
    range: 'The Model 3 also has an impressive range of up to 358 miles on a single charge, depending on the model. This range is comparable to that of many gas-powered vehicles, making the Model 3 an excellent option for long-distance driving.',
    eco: 'In addition to its impressive performance and range, the Model 3 is also incredibly eco-friendly. It produces zero emissions, which helps reduce air pollution and combat climate change. It\'s also incredibly energy-efficient, with an MPGe (miles per gallon equivalent) rating of up to 141 city/127 highway.',
    design: 'Another factor that sets the Model 3 apart is its sleek and modern design. The car\'s aerodynamic profile not only looks great, but it also helps reduce drag and increase efficiency. The interior is spacious and minimalist, with a large touchscreen display that controls everything from music to climate control.',
    safety: 'Finally, the Model 3 is equipped with an impressive array of safety features, including forward collision warning, automatic emergency braking, and adaptive cruise control. These features, combined with the car\'s low center of gravity and excellent handling, make it one of the safest cars on the road.',
  },
]

export default CarsTemp